import java.util.Random;
import java.util.ArrayList;
public abstract class Pet {
    private String name;
    private Random brain;
    // cutoff values
    protected int needFood, needSleep, needAttention;

    /**
     * Setter that allows for the specific pet's name to be added into the program output
     * @param name takes in the name the user inputs
     */
    public void setName(String name){
        this.name = name;
    }

    /**
     * Getter that retrieves the name of each individual pet so that it can be added to the output
     * @return returns the name so that it can be used in Simulate().
     */
    public String getName(){
        return name;
    }

    /**
     * Abstract method that sets cutoff values for each individual pet
     */
    public abstract void initializeCutOffs();

    /**
     * abstract method that gets the type of pet (cat/dog/fish)
     * @return the type of pet
     */
    public abstract String getType();

    /**
     * This abstract method compares the CutOff values to the values generated by the brain
     * to determine whether a specific action will be performed by a pet. The performed
     * actions are put into a list that will be used to print out all of a pet's actions
     */
    public abstract ArrayList<String> act();

    /**
     * Simulates a specified pet's actions over a specified number of hours, then generates a list for each hour
     * and formats them into a list. This will later be used to be printed in the ActivityPrinter
     * @param hourCount takes in the amount of hours the user wishes to simulate
     * @return An array list of formatted strings. The format is "The <pet type>, <pet name>, <action>."
     */
    public ArrayList<String> simulate(int hourCount) {
        ArrayList<String> activities = new ArrayList<>();
        for (int i = 0; i < hourCount; i++) {
            ArrayList<String> actions = this.act();
            for (String action : actions) {
                String activity = "The " + this.getType() + ", " + this.getName() + ", " + action + ".";
                activities.add(activity);
            }
        }
        return activities;
    }


}